# Generated by Django 5.2.2 on 2025-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('relation', models.CharField(choices=[('Self', 'Self'), ('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Other', 'Other')], max_length=20)),
                ('relation_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('occupation', models.CharField(choices=[('Government Service', 'Government Service'), ('Private Service', 'Private Service'), ('Business', 'Business'), ('Student', 'Student'), ('Retired', 'Retired'), ('Unemployed', 'Unemployed'), ('Other', 'Other')], max_length=50)),
                ('service', models.CharField(choices=[('Full Body Checkup', 'Full Body Checkup'), ('General Medicine', 'General Medicine'), ('Surgery', 'Surgery'), ('Pediatrics', 'Pediatrics'), ('Orthopedics', 'Orthopedics'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology')], max_length=50)),
                ('nationality', models.CharField(choices=[('India', 'India'), ('American', 'American'), ('British', 'British'), ('Canadian', 'Canadian'), ('Australian', 'Australian'), ('Other', 'Other')], max_length=50)),
                ('age_years', models.IntegerField(default=0)),
                ('age_months', models.IntegerField(default=0)),
                ('age_days', models.IntegerField(default=0)),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('identities', models.JSONField(blank=True, default=list)),
                ('insurance', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi'), ('Other', 'Other')], max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('biometric', models.BooleanField(default=False)),
                ('referred_by', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=20)),
                ('referred_doctor', models.CharField(max_length=100)),
                ('mobile_no_doctor', models.CharField(max_length=15)),
                ('message_to_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
