# Generated by Django 5.2.2 on 2025-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='referred_doctor',
            new_name='identity_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='identities',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile_no_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_type',
            field=models.CharField(choices=[('Aadhar No', 'Aadhar No'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID'), ('Other', 'Other')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_company',
            field=models.CharField(choices=[('HDFC ERGO', 'HDFC ERGO'), ('ICICI Lombard', 'ICICI Lombard'), ('Bajaj Allianz', 'Bajaj Allianz'), ('Star Health', 'Star Health'), ('Other', 'Other')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.CharField(default='exit', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
