# Generated by Django 5.2.6 on 2025-09-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='identity_type',
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('Aadhar No', 'Aadhar No'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID'), ('Other', 'Other')], max_length=50)),
                ('identity_number', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='app.patient')),
            ],
        ),
    ]
