# Generated by Django 5.2.2 on 2025-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_referred_doctor_patient_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_no_doctor',
            field=models.CharField(default='EXIT', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_doctor',
            field=models.CharField(default='EXIT', max_length=100),
            preserve_default=False,
        ),
    ]
