# Generated by Django 5.2.6 on 2025-09-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_patient_identity_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='identity_number',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='identity_type',
            field=models.CharField(choices=[('Aadhar No', 'Aadhar No'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID'), ('Other', 'Other')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
    ]
