# Generated by Django 5.2.6 on 2025-09-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient_identity_number_patient_identity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identity_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='identity_type',
        ),
        migrations.AddField(
            model_name='patient',
            name='identities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
