# Generated by Django 5.2.2 on 2025-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient_mobile_no_doctor_patient_referred_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referred_doctor',
            field=models.CharField(choices=[('SASTRI', 'SASTRI'), ('PRABHA', 'PRABHA'), ('JOHN', 'JOHN'), ('DEO', 'DEO')], max_length=100),
        ),
    ]
