# Generated by Django 5.2.2 on 2025-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_patient_referred_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='referred_doctor',
            field=models.CharField(choices=[('Sastri', 'Sastri'), ('Prabha', 'Prabha'), ('John', 'John'), ('Deo', 'Deo')], max_length=100),
        ),
    ]
