# Generated by Django 5.2.6 on 2025-09-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_patient_identity_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_number',
        ),
    ]
