# Generated by Django 5.2.2 on 2025-09-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_referred_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_no_doctor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relation',
            field=models.CharField(choices=[('Self', 'Self'), ('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Other', 'Other')], max_length=50),
        ),
    ]
