# Generated by Django 5.2.6 on 2025-09-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_patient_insurance_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
