# Generated by Django 5.2.6 on 2025-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_no_doctor',
            field=models.CharField(default='exit', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_doctor',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
