# Generated by Django 5.2.6 on 2025-09-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patient_mobile_no_doctor_patient_referred_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='identities',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.AlterField(
            model_name='patient',
            name='uhid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('Aadhar No', 'Aadhar No'), ('PAN', 'PAN'), ('Passport', 'Passport'), ('Driving License', 'Driving License'), ('Voter ID', 'Voter ID'), ('Other', 'Other')], max_length=50)),
                ('identity_number', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(choices=[('HDFC ERGO', 'HDFC ERGO'), ('ICICI Lombard', 'ICICI Lombard'), ('Bajaj Allianz', 'Bajaj Allianz'), ('Star Health', 'Star Health'), ('Other', 'Other')], max_length=100)),
                ('insurance_number', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='app.patient')),
            ],
        ),
    ]
